name: Auto Update and Restart Python Script

on:
  push:
    branches:
      - main  # Change to your branch name if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 35.223.35.59 >> ~/.ssh/known_hosts  # Replace with your GCE external IP

    - name: Stop running Python script, update code, and restart
      run: |
        ssh -i ~/.ssh/id_rsa gce-user@35.223.35.59 << 'EOF'
        # Kill any existing Python process running the script
        pkill -f main.py || echo "No running Python script found to stop"

        # Navigate to the repository and pull the latest code
        cd ~/bot/glacial-addons-bot/
        git pull

        # Activate the virtual environment
        source venv/bin/activate

        # Start the Python script in the background
        nohup python3 main.py > app.log 2>&1 &
        EOF
